# Generated by Django 4.2.1 on 2023-12-08 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='Stockholm', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_uploads', models.ImageField(upload_to='user/uploads')),
            ],
        ),
        migrations.CreateModel(
            name='UseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(upload_to='user/profile')),
                ('Banner_picture', models.ImageField(upload_to='user/profile')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('UserCompany', models.CharField(max_length=100, null=True)),
                ('Role', models.CharField(max_length=100, null=True)),
                ('Description', models.CharField(max_length=300, null=True)),
                ('PhoneNumber', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('CompanyNumber', models.IntegerField(null=True)),
                ('CompanyOpening', models.TimeField(default=django.utils.timezone.now)),
                ('CompanyClosing', models.TimeField(default=django.utils.timezone.now)),
                ('company_uploads', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='companies_uploaded', to='base.pictures')),
            ],
        ),
    ]
