# Generated by Django 4.2.1 on 2023-12-18 22:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ID', models.IntegerField(default=0)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='user/profile')),
                ('banner_picture', models.ImageField(blank=True, null=True, upload_to='user/profile')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300, null=True)),
                ('phone_number', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_uploads', models.ImageField(upload_to='user/uploads')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='base.useprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=200)),
                ('CompanyNumber', models.IntegerField(null=True)),
                ('CompanyOpening', models.TimeField(default=django.utils.timezone.now)),
                ('CompanyClosing', models.TimeField(default=django.utils.timezone.now)),
                ('companyEmail', models.CharField(max_length=400, null=True)),
                ('Address', models.CharField(default='unknown', max_length=300)),
                ('Stad', models.CharField(default='Stockholm', max_length=200)),
                ('Postnummer', models.CharField(default='1234', max_length=200)),
                ('Typ', models.CharField(default='unknown', max_length=100)),
                ('Bild', models.ImageField(blank=True, null=True, upload_to='user/find')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Company', to='base.useprofile')),
            ],
        ),
    ]
