# Generated by Django 4.2.1 on 2023-12-20 19:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
        migrations.AddField(
            model_name='company',
            name='user_ID_C',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='CompanyClosing',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='CompanyOpening',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
