# Generated by Django 4.2.1 on 2023-12-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='address',
            field=models.CharField(default='', max_length=300),
        ),
    ]
