# Generated by Django 4.2.1 on 2024-01-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_company_user_company_user_id_c_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='CompanyClosing',
        ),
        migrations.RemoveField(
            model_name='company',
            name='CompanyOpening',
        ),
        migrations.RemoveField(
            model_name='pictures',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='pictures',
            name='user_ID_P',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='Address',
            field=models.CharField(default='unknown', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='CompanyName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='Postnummer',
            field=models.CharField(default='1234', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='Stad',
            field=models.CharField(default='Stockholm', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='Typ',
            field=models.CharField(default='unknown', max_length=100, null=True),
        ),
    ]
