# Generated by Django 4.2.1 on 2023-12-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_addresses_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='Stjärnor',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='addresses',
            name='bild',
            field=models.ImageField(null=True, upload_to='user/find'),
        ),
        migrations.AddField(
            model_name='addresses',
            name='namn',
            field=models.CharField(default='unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='addresses',
            name='nummer',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='addresses',
            name='postnummer',
            field=models.CharField(default='1234', max_length=200),
        ),
        migrations.AddField(
            model_name='addresses',
            name='typ',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='address',
            field=models.CharField(default='unknown', max_length=300),
        ),
    ]
