# Generated by Django 4.2.1 on 2024-01-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_company_companyclosing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='profilePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ID_B', models.IntegerField(default=0)),
                ('company_uploads', models.ImageField(upload_to='user/profile')),
            ],
        ),
    ]
