# Generated by Django 4.2.1 on 2023-12-08 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_addresses_stjärnor_addresses_bild_addresses_namn_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresses',
            old_name='address',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='addresses',
            old_name='bild',
            new_name='Bild',
        ),
        migrations.RenameField(
            model_name='addresses',
            old_name='namn',
            new_name='Namn',
        ),
        migrations.RenameField(
            model_name='addresses',
            old_name='nummer',
            new_name='Nummer',
        ),
        migrations.RenameField(
            model_name='addresses',
            old_name='postnummer',
            new_name='Postnummer',
        ),
        migrations.RenameField(
            model_name='addresses',
            old_name='city',
            new_name='Stad',
        ),
        migrations.RenameField(
            model_name='addresses',
            old_name='typ',
            new_name='Typ',
        ),
    ]
