# Generated by Django 4.2.1 on 2024-01-04 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_profilepicture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilepicture',
            old_name='company_uploads',
            new_name='profile_uploads',
        ),
    ]
